import { Theme } from "@/types";
export const colors: Theme = {
  primary: {
    text: "text-emerald-500",
    textBase: "text-slate-200",
    h2: "text-emerald-600",
    h1: "text-emerald-400",
    border: "border-emerald-700",
    bg: "bg-slate-900",
    ring: "ring-emerald-500",
    shadow: "shadow-emerald-500",
  },
  secondary: {
    text: "text-fuchsia-500",
    textBase: "text-slate-200",
    h2: "text-fuchsia-600",
    h1: "text-fuchsia-400",
    border: "border-fuchsia-700",
    bg: "bg-slate-900",
    ring: "ring-fuchsia-500",
    shadow: "shadow-fuchsia-500",
  },
  gray: {
    text: "text-slate-500",
    textBase: "text-slate-200",
    h2: "text-slate-500",
    h1: "text-slate-800",
    border: "border-slate-700",
    bg: "bg-slate-900",
    ring: "ring-slate-500",
    shadow: "shadow-slate-500",
  },
  white: {
    text: "text-slate-500",
    textBase: "text-slate-800",
    h2: "text-slate-600",
    h1: "text-slate-800",
    border: "border-slate-600",
    bg: "bg-slate-100",
    ring: "ring-slate-500",
    shadow: "shadow-slate-500",
  },
  primaryGray: {
    text: "text-emerald-500",
    textBase: "text-neutral-300",
    h2: "text-emerald-600",
    h1: "text-emerald-400",
    border: "border-emerald-700",
    bg: "bg-slate-800",
    ring: "ring-emerald-500",
    shadow: "shadow-emerald-500",
  },
  secondaryGray: {
    text: "text-fuchsia-500",
    textBase: "text-neutral-300",
    h2: "text-fuchsia-600",
    h1: "text-fuchsia-400",
    border: "border-fuchsia-700",
    bg: "bg-slate-800",
    ring: "ring-fuchsia-500",
    shadow: "shadow-fuchsia-500",
  },
};
