export const boardNames: [
  "CBSE",
  "CISCE",
  "IB",
  "NIOS",
  "CAMBRIDGE",
  "STATE_BOARD",
  "OTHER",
] = ["CBSE", "CISCE", "IB", "NIOS", "CAMBRIDGE", "STATE_BOARD", "OTHER"];

export const orgTypes: ["SCHOOL", "TUTORIAL", "COLLEGE", "COMPANY", "OTHER"] = [
  "SCHOOL",
  "TUTORIAL",
  "COLLEGE",
  "COMPANY",
  "OTHER",
];

export const stateNames: [
  "Andhra_Pradesh",
  "Arunachal_Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal_Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya_Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil_Nadu",
  "Telangana",
  "Tripura",
  "Uttar_Pradesh",
  "Uttarakhand",
  "West_Bengal",
  "Andaman_And_Nicobar_Islands",
  "Chandigarh",
  "Dadra_And_Nagar_Haveli_And_Daman_And_Diu",
  "Lakshadweep",
  "Delhi",
  "Puducherry",
  "Jammu_And_Kashmir",
  "Ladakh",
] = [
  "Andhra_Pradesh",
  "Arunachal_Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal_Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya_Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil_Nadu",
  "Telangana",
  "Tripura",
  "Uttar_Pradesh",
  "Uttarakhand",
  "West_Bengal",
  "Andaman_And_Nicobar_Islands",
  "Chandigarh",
  "Dadra_And_Nagar_Haveli_And_Daman_And_Diu",
  "Lakshadweep",
  "Delhi",
  "Puducherry",
  "Jammu_And_Kashmir",
  "Ladakh",
];

export const languageMedium: ["ENGLISH", "HINDI"] = ["ENGLISH", "HINDI"];
