export const authConfig = [
  {
    type: "student",
    headline: "For Students",
    description:
      "Access your teacher's lesson plans, worksheets, activities and assessments with AI that is easy to use and strictly follows your syllabus.",
    buttonText: "Student Sign In",
    buttonVariant: "default",
    auth: "google-student",
    subtext: "Works on mobile phones and laptop.",
    image: "/chubbi.png",
    callbackUrl: "/dragon/student",
    userType: "STUDENT",
    inviteCallbackUrl: "/dragon/student/invite",
    decorationColor: "decoration-primary",
  },
  {
    type: "teacher",
    headline: "For Teachers",
    description:
      "Access your teacher's lesson plans, worksheets, activities and assessments with AI that is easy to use and strictly follows your syllabus.",
    buttonText: "Teacher Sign In",
    buttonVariant: "secondary",
    auth: "google",
    subtext: "Works on large screens only.",
    image: "/chubbi.png",
    callbackUrl: "/dragon/teacher",
    userType: "TEACHER",
    inviteCallbackUrl: "/dragon/teacher/invite",
    decorationColor: "decoration-secondary",
  },

  {
    type: "org-admin",
    headline: "For Administrators",
    description:
      "Access your teacher's lesson plans, worksheets, activities and assessments with AI that is easy to use and strictly follows your syllabus.",
    buttonText: "Admin Sign In",
    buttonVariant: "secondary",
    auth: "google-org-admin",
    subtext: "Works on large screens only.",
    image: "/chubbi.png",
    callbackUrl: "/dragon/org-admin",
    userType: "ORG_ADMIN",
    inviteCallbackUrl: "/dragon/org-admin/invite",
    decorationColor: "decoration-secondary",
  },
  {
    type: "parent",
    headline: "For Parents",
    description:
      "Access your teacher's lesson plans, worksheets, activities and assessments with AI that is easy to use and strictly follows your syllabus.",
    buttonText: "Parent Sign In",
    buttonVariant: "secondary",
    auth: "google-parent",
    subtext: "Works on large screens only.",
    image: "/chubbi.png",
    callbackUrl: "/dragon/parent",
    userType: "PARENT",
    inviteCallbackUrl: "/dragon/parent/invite",
    decorationColor: "decoration-secondary",
  },
] as const;
